### ISSUE TITLE
Undocumented property `value_type` in Array field 

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav-learn#1043]
The Array field introduced in the Form plugin [has an undocumented property `value_type`](https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/array/array.html.twig#L21) which can be set to `value_type: textarea` to change the value entry element from an `<input>` to a `<textarea>`.

![image](https://user-images.githubusercontent.com/8947634/196682733-a87bbb83-0e69-4caf-9e7d-ee6db8d24d53.png)
![image](https://user-images.githubusercontent.com/8947634/196682866-a8a516e1-bfcb-4ec2-a7a9-57d8df69658c.png)

This is useful, but undocumented.

Shall I document this, or is there a reason why it's not in the docs at the moment?

**Comment by rhukster** [comment]
Please document it :)

It's very hard for me to keep the code and docs in sync by myself so any help is appreciated.
