### ISSUE TITLE
Commands not Found

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-learn#105]
While installing grav-learn through ssh I am getting several "Commands not Found" during the Cloning Bits phase of the installation, suggestion?

**Comment by rhukster** [comment]
I'll look into this.  I know the installation process needs updating to reflect the changes made to support the new learn design.

**Comment by rhukster** [comment]
Please try this with the https://github.com/getgrav/grav-skeleton-rtfm-site

**Comment by ghost** [comment]
THX! ... Look forward to it!
