### ISSUE TITLE
Functions PCRE (regex?) error

### ISSUE THREAD

**Issue by sapphicdisaster** [getgrav/grav-learn#1088]
The page https://learn.getgrav.org/16/themes/twig-tags-filters-functions/functions currently returns "Whoops there was an error! 0 - PCRE failure `4`." 
May be a syntax issue e.g. missing escape character on quote?

**Comment by pmoreno-rodriguez** [comment]
Now it's ok.

**Comment by rhukster** [comment]
yes i fixed this.
