### ISSUE TITLE
List into Notices ?

### ISSUE THREAD

**Issue by reyman** [getgrav/grav-learn#128]
Is it possible to add list into notices,
 i have weird result when i try

**Comment by rhukster** [comment]
can you give me an example?

**Comment by reyman** [comment]
> > > NOTE : 
> > > - V0.1 Aout 2015 : première version du manuscrit

see result on these.sebastienreycoyrehourcq.fr

**Comment by rhukster** [comment]
This appears to be a limitation in markdown and/or parsedown library we are using.  I can't fix that.
