### ISSUE TITLE
Permissions troubleshooting page should account for files in bin

### ISSUE THREAD

**Issue by nickanderson** [getgrav/grav-learn#129]
The example script shows setting all files to 644, this will remove the executable bit from bin/grav and bin/gpm.

If the script is intended to be run from the top of the grav install
find . -type f ! -path "./bin/_" | xargs chmod 644
find . -type f -path "./bin/_" | xargs chmod 755

**Comment by nickanderson** [comment]
https://github.com/getgrav/grav-learn/blob/develop/pages/09.troubleshooting/05.permissions/docs.md

**Comment by austinbutler** [comment]
Heh, just ran into this myself. Definitely confusing in the manual, and if you try sudo with gpm from getting an error you end up with bad permissions all over, breaking the site.

**Comment by rhukster** [comment]
thanks, have updated the docs with this
