### ISSUE TITLE
Github plugin missing on learn.getgrav.org?

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-learn#130]
Grav versions are not showing up in the learn.getgrav.org site, locally I installed the `github` plugin and then they worked.

![screen shot 2015-08-17 at 12 29 38](https://cloud.githubusercontent.com/assets/11783388/9303029/a6f86080-44db-11e5-9930-617b2a1ae5c0.png)

**Comment by rhukster** [comment]
GitHub plugin was tehre, but out of date, maybe it was related to that.  I've updated it on learn.getgrav.org
