### ISSUE TITLE
Bitbucket authentication?

### ISSUE THREAD

**Issue by attiks** [getgrav/grav-learn#145]
Is this standard bitbucket behavior?

```
Cloning into 'user/plugins/gravui'...
Username for 'https://bitbucket.org': attiks
Password for 'https://attiks@bitbucket.org': 
remote: Unauthorized
fatal: Authentication failed for 'https://bitbucket.org/rockettheme/grav-plugin-gravui/'
SUCCESS cloned https://bitbucket.org/rockettheme/grav-plugin-gravui -> /home/peter/projecten/grav-learn//user/plugins/gravui
```

Cause by https://github.com/getgrav/grav-learn/blob/develop/.dependencies#L22

**Comment by rhukster** [comment]
GravUI is not a publically release plugin.  it's used for the tabs display, but it's a bit hacky and i'm not proud of it!  We use it in Grav learn, but it should probably not be included in the dependencies

**Comment by attiks** [comment]
But I assume I can update (and test) the docs without it?

**Comment by rhukster** [comment]
yah it's still usable without that plugin

**Comment by Sogl** [comment]
@rhukster This problem is still here:

![image](https://cloud.githubusercontent.com/assets/7556290/22630777/dd708bda-ec53-11e6-845f-1eea9cabca22.png)
