### ISSUE TITLE
Pagination next is not working on sub-sub menu

### ISSUE THREAD

**Issue by 810** [getgrav/grav-learn#149]
When you click on the next page, it goes to the next page. But if you have sub-sub menu. It only go to the sub menu.

example:
http://www.jellekoksolutions.nl/docs2/manual/backend/tools/prune-categories

click next page

**Comment by rhukster** [comment]
Site seems to be down.

**Comment by rhukster** [comment]
And back up.

**Comment by rhukster** [comment]
And down again. Bah.. i can't tell what's going on with it up and down like this.

**Comment by 810** [comment]
yeah, looks like cloudflare does't like the cache, everytime when I save a blog, I get a error. when refresh its ok.

**Comment by 810** [comment]
I have asked the person to stop working on the docs right now, so now you can check it, without any error.

**Comment by rhukster** [comment]
BTW, just tested this with my own setup http://learn.getgrav.org/hosting/vps/linode and it works fine. 

You need to make sure that each page has the appropriate taxonomy:

```
taxonomy:
    category: docs
```

The collection that is iterated over for the prev/next pagination is this:

```
{% set tags = page.taxonomy.tag %}
{% if tags %}
    {% set progress = page.collection({'items':{'@taxonomy':{'category': 'docs', 'tag': tags}},'order': {'by': 'default', 'dir': 'asc'}}) %}
{% else %}
    {% set progress = page.collection({'items':{'@taxonomy':{'category': 'docs'}},'order': {'by': 'default', 'dir': 'asc'}}) %}
{% endif %}
```

If your having trouble, then this collection is not being built correctly. This really relates to your content more than anything.

**Comment by 810** [comment]
Ok, I set all pages, to docs.

Chrome:
chapter->chapter->chapter->doc = When click next/prev links to the page itself 
http://www.jellekoksolutions.nl/docs2/en/manual/backend/tools/prune-categories

IE:
chapter->chapter->chapter->doc = When click next/prev links to chapter http://www.jellekoksolutions.nl/docs2/en/manual/backend/tools/
