### ISSUE TITLE
Media display in templates

### ISSUE THREAD

**Issue by AlexandreBroudin** [getgrav/grav-learn#175]
This snippet was not working until `markdown extra` was set to true

```
{% for child in collection %}
  {{ child.media['cover.jpg'].display('thumbnail').html() }}
{% endfor %}  
```

Maybe a little info box saying that `Markdown extra` has to be set to `true` to make it works would be appreciated

**Comment by rhukster** [comment]
That should not need markdown extra, can you test with this and no markdown extra:

```
{% for child in collection %}
{{ child.media['cover.jpg'].display('thumbnail').html() }}
{% endfor %}  
```

notice the lack of space before the `{{`

**Comment by AlexandreBroudin** [comment]
Hum ok, maybe it was just cache, now it works well with or without markdown extra.
