### ISSUE TITLE
Image missing/wrong link in 01.general-recipes

### ISSUE THREAD

**Issue by Bokelmann** [getgrav/grav-learn#199]
grav-learn/pages/08.cookbook/01.general-recipes/docs.md
http://learn.getgrav.org/cookbook/general-recipes#problem-3

The link <img src="http://5to9design.ca/images/recent-pages.png" alt="Recent post widget">
Does not seem to exist ...

**Comment by flaviocopes** [comment]
Thanks for the notice, it's an external image and cannot be found anymore
