### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by gitname** [getgrav/grav-learn#210]
The sentence shown in the attached screenshot (of [this page](http://learn.getgrav.org/admin-panel/pages-admin)) is incomplete.

![grav-missing-text](https://cloud.githubusercontent.com/assets/7143133/12069021/d6061380-afd0-11e5-8079-f10d5a21c1eb.png)

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed
