### ISSUE TITLE
Contact form: Demo is broken

### ISSUE THREAD

**Issue by tobias-forkel** [getgrav/grav-learn#214]
The contact form behind the link " Live page " ( http://demo.getgrav.org/soraarticle-skeleton/contact ) is broken.

Source: https://github.com/getgrav/grav-learn/blob/develop/pages/06.advanced/14.contact-form/docs.md

**Comment by flaviocopes** [comment]
While the issue does not belong to this repository, I just tried to install skeleton locally and it works fine. Can you confirm?

Maybe it's an issue related to the deploy of the skeleton, @rhukster ?

**Comment by flaviocopes** [comment]
Fixed on the demo, was a server deployment-related issue
