### ISSUE TITLE
Why am i getting "not found 404 page" when trying to navigate through the local copy of the documentation

### ISSUE THREAD

**Issue by ismnoiet** [getgrav/grav-learn#217]
I've just  installed a local copy of _grav-learn_ to read the documentation offline, the main page(first page) appears just as expected but where trying to move to another page i get the **404** page.
Is there any configuration to put inside   `.htaccess` file or something like that ?

Thank you in advance.

**Comment by rhukster** [comment]
http://learn.getgrav.org/troubleshooting/page-not-found

Your server needs to have all the bits for url rewriting enabled.

**Comment by ismnoiet** [comment]
Thank you for the support.
