### ISSUE TITLE
Page object summary() documentation clarification

### ISSUE THREAD

**Issue by karlding** [getgrav/grav-learn#236]
The [documentation](http://learn.getgrav.org/themes/theme-vars#summary) is a little misleading with regards to `summary()`.

```
This returns a truncated or shortened version of your content. You can provide an optional 
size parameter to specify the number of words. Alternatively, if no size is provided, the 
value can be obtained via the site-wide variable summary.size from your site.yaml configuration.
```

However, `summary(size)` limits by the **number of characters**, not the **number of words**, which is evident in `system/src/Grav/Common/Page/Page.php`.

Should the documentation be updated to clarify that it is the number of characters that're being limited, and not the words? Or is this an oversight and summaries were intended to be based on the number of words?

**Comment by rhukster** [comment]
Thanks, closing this now.
