### ISSUE TITLE
mongoose server?

### ISSUE THREAD

**Issue by shane0** [getgrav/grav-learn#247]
Has anyone tried running grav on mongoose?   should be easy and can add that to the list of grav supported servers

https://github.com/cesanta/mongoose

I'm using the windows binary php version and I can get the grav home page to display but no others, I suspect I'm just having a folder permissions issue to get past, I'll update this if I get further

**Comment by rhukster** [comment]
Never heard of it.  Most likely you will need to recreate the rewrite rules for this sever.  That's probably why the first page shows and not others.

**Comment by shane0** [comment]
Found some references, I'll try configuring rewrites later it should work.

https://docs.cesanta.com/mongoose/dev/#/c-api/http.h/struct_mg_serve_http_opts/

![mongoose](https://cloud.githubusercontent.com/assets/1454458/15265224/12277ff8-1934-11e6-8695-9c95f6df3cdc.PNG)

**Comment by shane0** [comment]
actually, I just updated my mongoose pro and noticed they stopped supporting php so skip this, I'm goign to swtich to nginx
