### ISSUE TITLE
Add more information on blueprint form types, e.g. array and list

### ISSUE THREAD

**Issue by toovy** [getgrav/grav-learn#254]
Hi grav-team,

the doc is really awesome. Personally I think that more advanced form field types like array and list, maybe some others too, aber not really documented. Also google does not really help. It is really hard to get started. Maybe I've missed sth.

Thanks & BR toovy

**Comment by flaviocopes** [comment]
@toovy good point. Want to properly document each field very soon.

**Comment by toovy** [comment]
@flaviocopes I'm a bit under time pressure, but if you could point me to the source code where I could analyze how that stuff works I would probably be able to support.

**Comment by flaviocopes** [comment]
Sure, 

Fields also available in the frontend forms:
https://github.com/getgrav/grav-plugin-form/tree/develop/templates/forms/fields

Fields only available in admin forms (blueprints):
https://github.com/getgrav/grav-plugin-admin/tree/develop/themes/grav/templates/forms/fields

I'd like to start documenting them in http://learn.getgrav.org/forms/blueprints/reference-fields-available (admin) and http://learn.getgrav.org/forms/forms/reference-fields-available (frontend) 

Like already done for the File field here: http://learn.getgrav.org/forms/forms/reference-fields-available#the-file-field

**Comment by flaviocopes** [comment]
Started adding the Text field https://github.com/getgrav/grav-learn/commit/c7ab413407c60b02ae793f0bbdf66d7f1ddfa837 maybe the others can follow the same structure. Listing all the common fields, point to the general fields list, and if the field accepts special attributes, describe them

**Comment by flaviocopes** [comment]
`captcha` https://github.com/getgrav/grav-learn/commit/74a8d5ece52131181efb9702dbe9f835a531bf39

**Comment by flaviocopes** [comment]
All Frontend fields are covered in http://learn.getgrav.org/forms/forms/reference-fields-available
Next is Admin fields

**Comment by toovy** [comment]
@flaviocopes that is what I call a lightning fast reaction. Thank you very much. I've analyzed the plugins so I could support - if support is needed. I could update the documentation as you proposed for a couple of modules. Just tell me what you are working on so that we don't do overlapping work.

**Comment by flaviocopes** [comment]
Currently working on another page, for admin-side form fields, you can edit that page freely.

**Comment by toovy** [comment]
Just to be precise, I would work on this page:
http://learn.getgrav.org/forms/blueprints/reference-fields-available

**Comment by flaviocopes** [comment]
Ah wait then, I'm reworking it now :)

**Comment by flaviocopes** [comment]
Page updated! You can tweak / add / suggest edits. http://learn.getgrav.org/forms/blueprints/reference-fields-available

**Comment by toovy** [comment]
I'm absolutely fine with it. Thanks!

**Comment by happywky** [comment]
May I start to translate a Chinese version of http://learn.getgrav.org/ ?
Just fork it and upload the Chinese version to my azure? Maybe you have better idea..

**Comment by flaviocopes** [comment]
@happywky you're free to translate it

**Comment by flaviocopes** [comment]
@happywky currently we have no plans of managing documentation translations ourselves, if that was intended in your question.
