### ISSUE TITLE
new skeleton based on grav-learn

### ISSUE THREAD

**Issue by eisenherzz** [getgrav/grav-learn#26]
Your documentation looks pretty good. Based on this what do you think about a "grav-skeleton-documentation" or "grav-skeleton-book"?

**Comment by rhukster** [comment]
It's not a bad idea actually :)  We already have our learn.getgrav.org site on github, but it's not a ready-to-install skeleton.  We would need tidy up the theme a bit (its a bit scruffy), but something i'll put down on the list! Thanks.

**Comment by eisenherzz** [comment]
https://github.com/getgrav/grav-theme-learn2 should solve the issue ;)

**Comment by rhukster** [comment]
Actually the one you want is the RTFM skeleton:  https://github.com/getgrav/grav-skeleton-rtfm-site

ready-to-go pre-built package is on getgrav.org:

http://getgrav.org/downloads/skeletons
