### ISSUE TITLE
strange markdown wrapping

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-learn#272]
hi guys, after the last update it seems the learn site has an issue with wrapping markdown and normal text as per the picture attached.
![captura de ecran din 2016 04 27 la 17 39 23](https://cloud.githubusercontent.com/assets/7076631/14860123/2eb9668c-0c9f-11e6-866e-19b77150e9b5.png)

**Comment by rhukster** [comment]
Yah looks broken for me too.. will fix..

**Comment by flaviocopes** [comment]
Probably caused by https://github.com/getgrav/grav-learn/commit/7e0d0d03a565a3e4d015a810ce34163720b53183
