### ISSUE TITLE
What lang is this?

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-learn#276]
https://learn.getgrav.org/content/media#where-to-put-your-media-files

Up until now the docs have only been discussing Markdown exmamples... this line:

page.find('/images').media['my-image.jpg']

is it MD? Twig?

**Comment by rhukster** [comment]
Twig.. but you can put Twig in markdown if you enabled `process: twig: true`. Just needs to be wrapped in `{{ }}` tags.
