### ISSUE TITLE
MD Extra needed?

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-learn#277]
Here: https://learn.getgrav.org/content/media#general

It states that `![Some ALT text](sample-image.jpg "My title") {.myclass}`

would be how you add a class and then there's a notice that states:

To use classes in Markdown, you need to enable Markdown Extra.

However, back here:

https://learn.getgrav.org/content/image-linking#image-attributes

it states that classes are natively supported in MD

**Comment by rhukster** [comment]
Originally you needed markdown extra to use the `{.myclass}` type syntax to add a class. But now we have added image and link attributes via `?classes=myclass` and for that you don't need markdown extra.

This was added much later, but the markdown extra syntax is still a valid option.
