### ISSUE TITLE
Is the required Grav Version for the Admin Plugin correct?

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-learn#278]
https://learn.getgrav.org/admin-panel/introduction#installation

Says: Grav 1.1.0-beta.4 or later

I'm on 1.0.10 stable ~ and the Admin plugin seems fine?

**Comment by rhukster** [comment]
1.0.10 stable is fine.  I need to change how we get the 'latest' version.. should only be stable listed there, but it's picking up the betas.
