### ISSUE TITLE
Wrong method name in Media-Documentation

### ISSUE THREAD

**Issue by weltenbauer** [getgrav/grav-learn#289]
Hey Guys,

in the doc file [grav-learn/pages/02.content/07.media/docs.md](https://github.com/getgrav/grav-learn/blob/develop/pages/02.content/07.media/docs.md#cropzoomwidth-height) the image cropZoom function should be renamed to zoomCrop as documented in this repo (https://github.com/Gregwar/Image).

Cheers,
Christian

**Comment by flaviocopes** [comment]
We have an alias, you can do both in Grav.

**Comment by weltenbauer** [comment]
Oh ok. But is it possible that something went wrong there? In my grav installation (v1.0.10) cropZoom is not working. But maybe a problem on my side?

**Comment by flaviocopes** [comment]
No, it should work. Is zoomCrop working instead?

**Comment by weltenbauer** [comment]
zoomCrop is working as expected. That's why I thought it was a typo in the docs.

**Comment by flaviocopes** [comment]
Tested, both work fine to me. How do you use it, can you paste the Twig line?

**Comment by weltenbauer** [comment]
Hey flavio. I use it that way:
`<div class="content__image" style="background-image: url({{ page.url }}/{{ header.image }}?cropZoom=1180,507)" data-height-ratio="0.43"></div>`

**Comment by flaviocopes** [comment]
`?cropZoom` is supposed to work when used in a Markdown link, not in this way. You probably see it in the HTML generated, right? In twig, use `{{ header.image.cropZoom(600,200).url }}`

**Comment by RyanMPierson** [comment]
Added a note re: zoomCrop in the documentation.
