### ISSUE TITLE
Build an epub

### ISSUE THREAD

**Issue by cpamcom** [getgrav/grav-learn#314]
Could you please make it possible to build an epub file with the learn.getgrav.org website?
Would be a very nice option of the documentation!

Thanks
C

**Comment by flaviocopes** [comment]
While a cool idea, it's not really practical as we constantly update the docs and you might download it once, never update it, while the docs are improved on the live site. Plus, the docs contain many code snippets which would not render nicely in epub.

**Comment by cpamcom** [comment]
I understand. But my need is to take it away, read it on the e-reader offline

**Comment by RyanMPierson** [comment]
There is a method you can use to make a PDF of the documentation, but it takes a little elbow grease and patience. A lot of markdown editors, including Mou, Atom.io, and I believe also Sublime Text with the right plugins, can export markdown files to PDF. What you could do is export the github project for documentation in PDF, then stitch them together into an epub.

You might need to edit out the YAML frontmatter, but it would be one way to do it. Again, it'll take a lot of work and wouldn't be something our team would have time to do each time we update the documentation.

Hope this helps!

**Comment by RyanMPierson** [comment]
Closing this since it's a change we don't intend to make at the present. However, we may revisit this if there is sufficient demand and documentation reaches a more stable state. Currently there is still a lot of new features being added and moving parts.
