### ISSUE TITLE
Incomplete Description in Common Field Attributes Table

### ISSUE THREAD

**Issue by itsmattsoria** [getgrav/grav-learn#318]
There is an incomplete description in the [Common Field Attributes](https://learn.getgrav.org/forms/blueprints/fields-available#common-fields-attributes) table for the `style` attribute:

<img width="689" alt="screen shot 2016-09-21 at 11 45 26 am" src="https://cloud.githubusercontent.com/assets/2831517/18720307/edd5d996-7ff0-11e6-8d2b-ab564ff75c5a.png">

**Comment by rhukster** [comment]
@FrugalGeek you mind looking at this when you work on the other docs related item today?

**Comment by RyanMPierson** [comment]
No problem!
