### ISSUE TITLE
Broken YAML SYNTAX example

### ISSUE THREAD

**Issue by Frodox** [getgrav/grav-learn#347]
Here is example: https://github.com/getgrav/grav-learn/blob/develop/pages/08.advanced/11.yaml/docs.md#mappings

```yml
animal: pets
- Cat
- Dog
- Goldfish
```

but it doesn't work in pyyaml and http://www.yamllint.com/ with error:
```
yaml.parser.ParserError: while parsing a block mapping
  in "test.yml", line 1, column 1
expected <block end>, but found '-'
  in "test.yml", line 2, column 1
```

I could fix it, but I'm not sure I'm clear with goal of example..

**Comment by flaviocopes** [comment]
I have no idea too what that example should do, and also it does not work in Grav pages frontmatter.

Also the examples above (nested sequences without a name for the parent item) are very rarely (never seen them) used in Grav.

**Comment by Frodox** [comment]
So, can I just rewrite this part with examples?

**Comment by flaviocopes** [comment]
Yes please 👍
