### ISSUE TITLE
Install requirements for Mac with brew

### ISSUE THREAD

**Issue by rogervila** [getgrav/grav-learn#359]
Hello,

It would be nice to show how to install new Php and apache or nginx versions with brew on the [requirements page](https://learn.getgrav.org/basics/requirements).

**Comment by w00fz** [comment]
You mean a link to https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions ?

**Comment by rogervila** [comment]
Yes, just under the Mamp option (which I would remove completly, since Mamp does not have any sense nowadays, but is just an opinion)

**Comment by flaviocopes** [comment]
Might not have any sense for you, but MAMP actually is one of the best options that "just work" to have a local server setup in 2 minutes, probably the best option if you're not a developer and just want to try Grav locally

**Comment by rogervila** [comment]
Yes, as I said it's just an opinion. I personally use Laravel Valet. I'll make the pull request with the blog link.
