### ISSUE TITLE
Missing closing parenthesis

### ISSUE THREAD

**Issue by adrian5** [getgrav/grav-learn#370]
Feels silly to open a ticket for this, but the [Basics > Installation](https://github.com/getgrav/grav-learn/blob/develop/pages/01.basics/03.installation/docs.md) section reads:
> You can replace the port number (in our example it's 8000 with any port you prefer.

I imagine `8000)` was intended.

**Comment by rhukster** [comment]
Fixed.  In the future, you can fix by just clicking the "edit in github" button at the top of the page.  make your change, and a PR is automatically created.

**Comment by adrian5** [comment]
Sorry, I wasn't aware of that ability. I'll be sure to use of it, if I ever run into anything else. Thanks!
