### ISSUE TITLE
Common fields attribute: Option outerclasses 

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-learn#440]
https://learn.getgrav.org/forms/forms/fields-available#common-fields-attributes

Docs mention an outerclasses option but it seems like it doesn't work and searching for this attribute in the whole plugin does not output anything.

**Comment by flaviocopes** [comment]
outerclasses works in the frontend forms, which are the ones described in the Learn page you listed, but not in Admin, currently. I saw the PR.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-admin/pull/1124

**Comment by RyanMPierson** [comment]
PR was merged later that month. Closing pending any further requests.
