### ISSUE TITLE
Section on permissions is confusing.

### ISSUE THREAD

**Issue by adrian5** [getgrav/grav-learn#443]
https://learn.getgrav.org/basics/requirements#permissions

> 2. Change the group permissions on all files and folders so that the webserver's group has write access to files and folders while keeping the standard permissions. This requires a few commands to make this work (note: adjust www-data to be the group your apache runs under [www-data, apache, nobody, etc.]):
> 
> ```
> chgrp -R www-data .
> find . -type f | xargs chmod 664
> find . -type d | xargs chmod 775
> find . -type d | xargs chmod +s
> umask 0002
> ```

What are the *standard permissions* talked about here, which are being kept? The second sentence could see better wording too.

I ran into permission issues, and more clarity/details in this section would be helpful.

**Comment by paulmassen** [comment]
Here is my try at clarifying this: https://github.com/getgrav/grav-learn/pull/460

It's kind of a duplicate with the troubleshooting section though.

Let me know if it seems more clear for you.

**Comment by adrian5** [comment]
I think my confusion lies in a different direction. If – following the example – one manually sets permissions to 775/664 and bases ownership on this assumption (e.g. `php:webserver`), doesn't Grav (or rather the PHP master process) need be _run_ with a umask of `0002` so that the site can handle files it created itself through uploads, plugins, updates? Or does Grav use chmod internally when writing files to ensure permissions are sound?

That's where I would like to see some more detail in the commentary, even if just lay beginner's concerns to rest. I don't think instructions should be Apache-specific at that point at all, even if it's the most popular webserver by far.

**Comment by adrian5** [comment]
By the way, [this](https://learn.getgrav.org/troubleshooting/permissions) is bogus:

> By using a shared Group between your user and PHP/Webserver account with 775 and 664 permissions you ensure that even though you have two different accounts, both will have Read/Write access to the files. **You should also probably set a umask 0002 on the root so that new files are created with the proper permissions**.

A umask cannot be "set" for a directory.

**Comment by flaviocopes** [comment]
That section in the requirements doc seems to duplicate what we have in more details in https://learn.getgrav.org/troubleshooting/permissions - @paulmassen I see you made a PR on that, I think we can remove any reference to permissions in the requirements document, and just link to the detailed permissions document (and merge the information, if necessary)

Otherwise we're duplicating the effort.

**Comment by paulmassen** [comment]
@flaviocopes yes, feel free to delete my PR on the install section. 
I'm not a bash specialist, but don't you think we could improve the script by setting a var such as :
```
HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
```

and then use $HTTPDUSER 

or something similar?

**Comment by paulmassen** [comment]
What about a new permission fixing script like this:

```
#!/bin/sh
HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
HTTPDUSERGROUP=`id $HTTPDUSER -gn`

chown -R $HTTPDUSER:$HTTPDUSERGROUP .
find . -type f | xargs chmod 664
find ./bin -type f | xargs chmod 775
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
```

**Comment by paulmassen** [comment]
Just tried on some install and it seems to work.
Might be worth to note in the docs that in order for this to work, apache or nginx must be running and that the script must be ran in the grav root directory

**Comment by adrian5** [comment]
How are your experiences regarding the persistence of these changed permissions? Do they survive major Grav updates? If not, I think the article should mention when to run the script again.

If the user has full control of the system, they could also run PHP with a different `umask`, which _would_ be persistent. With systemd, it's as simple as typing `sudo systemctl edit your.php.service` and setting a different umask in the created override file:

    [Service]
    UMask=0002

Followed by:

    sudo systemctl daemon-reload
    sudo systemctl restart your.php.service

**Comment by adrian5** [comment]
Ima close this issue, I doubt it still has relevance.
