### ISSUE TITLE
Typo in example of accessing "header" map

### ISSUE THREAD

**Issue by afhrad** [getgrav/grav-learn#47]
Hey guys,
I think there is a typo in the documentation where access of the pages headers map is written about.
It says "page.headers.author" for instance. In my opinion it should read "page.header.author" instead.
It took me a while to find out why a custom header variable was not printed in a twig template.
But maybe I am wrong, who knows ;-)
Cheers
Thorsten

**Comment by rhukster** [comment]
You are correct! Good catch.  You know you can edit the file right here on github and it will automatically create a pull request that we can simply merge in.  Do you want to try that? We can fix it ourselves, but its better if you do it, then we can keep track of who to credit, plus it's easier :)

**Comment by rhukster** [comment]
Specifically this page:

https://github.com/getgrav/grav-learn/blob/develop/pages/03.themes/04.theme-vars/docs.md

**Comment by rhukster** [comment]
Thanks for sorting
