### ISSUE TITLE
Broken link in api reference

### ISSUE THREAD

**Issue by oesni** [getgrav/grav-learn#483]
First item at navigation bar of [grav api reference](https://learn.getgrav.org/api/index.html) "Grav" is linked to [https://learn.getgrav.org/api/.html](https://learn.getgrav.org/api/.html).
I think that should be [https://learn.getgrav.org/api/Grav.html](https://learn.getgrav.org/api/Grav.html).

**Comment by RyanMPierson** [comment]
The page you're referencing is a 404, and I'm not finding any links that match your description. Can you provide a screenshot to help narrow down the search?
