### ISSUE TITLE
Can't find the page ? 

### ISSUE THREAD

**Issue by MikeMaldini** [getgrav/grav-learn#498]
When i access the 'Configuration' page, it can't be found !? Any other is fine ?

![image](https://user-images.githubusercontent.com/29230494/30650687-20071680-9e56-11e7-9e3c-ed507e9e18c3.png)

**Comment by rhukster** [comment]
https://learn.getgrav.org/basics/grav-configuration works fine for me.  You look like you have a local copy, are you sure everything is there and up to date?

**Comment by RyanMPierson** [comment]
Closing as there has been no response from OP. Does not appear to be a documentation issue.
