### ISSUE TITLE
Theme Learn4 Does Not Exist -Unable to Display Page

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-learn#714]
Just downloaded grav-learn and followed the steps on a working 1.6.9 install. No obvious errors, just messages:

```
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
    Skipped installation of bin bin/minifycss for package matthiasmullie/minify: file not found in package
    Skipped installation of bin bin/minifyjs for package matthiasmullie/minify: file not found in package
```

When I attempt to browse the site, I get "Theme 'learn4' does not exist, unable to display page." Same message for /admin login as well. There is a learn4 file (not folder) under themes, but it shows up as an alias on my macOS system.

**Comment by rhukster** [comment]
the public learn site has been updated to use learn4 (a new theme I developed).  This learn4 theme is publically available, but not officially released: https://github.com/getgrav/grav-theme-learn4
