### ISSUE TITLE
Readme install steps don't work

### ISSUE THREAD

**Issue by cberkom** [getgrav/grav-learn#78]
I'm getting this error:

```
Theme 'learn2' does not exist, unable to display page.
```

Is there a reason it can't find the theme? I ran `bin/grav install` as instructed.

**Comment by cberkom** [comment]
I found the theme broken out as it's [own repo here](https://github.com/getgrav/grav-theme-learn2), but running `bin/gpm install learn2` returns:

```
Nothing to install.
```

**Comment by rhukster** [comment]
"learn2" theme has not been added to GPM yet. You will need to install it by cloning the repo into your `user/themes/` folder as `learn2`.  

Make sure its the **develop** branch

**Comment by cberkom** [comment]
Got it, thanks!
