### ISSUE TITLE
Add example about deferred blocks

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-learn#829]
https://github.com/getgrav/grav-learn/blob/develop/pages/03.themes/04.twig-tags/docs.md
https://learn.getgrav.org/16/themes/twig-tags#deferred-blocks

It would be nice to add an example that contains `{{ parent() }}`, for example taken from quark theme:
```
{% block stylesheets %}
    {% do assets.addCss('theme://css/bricklayer.css') %}
    {{ parent() }}
{% endblock %}
```

**Comment by rhukster** [comment]
Why not do a pull request?

https://guides.github.com/activities/hello-world/#pr

**Comment by rhukster** [comment]
I guess you already know how :)

**Comment by NicoHood** [comment]
Sorry for the delay. https://github.com/getgrav/grav-learn/pull/850
