### ISSUE TITLE
Sentence is not understandable

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-learn#848]
https://github.com/getgrav/grav-learn/blob/develop/pages/03.themes/06.theme-vars/docs.md#home_url-variable

> The {{ home_url }} is particularly useful to use to link back to the homepage of your site. It is similar to base_url **but takes into account the situation when the this is empty.**

**Comment by rhukster** [comment]
Feel free to submit a PR with improved verbage.

**Comment by NicoHood** [comment]
Yeah, I'd love to, but I do really have no idea what the sentence would mean.

**Comment by mahagr** [comment]
```
'home_url' => $pages->homeUrl($active_language)
```

So it looks like it's just pointing to the home page of the current language.

**Comment by NicoHood** [comment]
The {{ home_url }} is particularly useful to use to link back to the homepage of your site. It is similar to base_url but takes the currently active language into account.

Does this sound good to you?

**Comment by rhukster** [comment]
yup sounds fine 👍

**Comment by NicoHood** [comment]
https://github.com/getgrav/grav-learn/pull/852
