### ISSUE TITLE
Server error on docs page

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-learn#880]
[Twig filters and functions page](https://learn.getgrav.org/17/themes/twig-filters-functions) gives this

> Server Error
> Sorry, something went terribly wrong!
> 
> 0 - An exception has been thrown during the rendering of a template ("Division by zero") in "@Page:/srv/users/serverpilot/apps/learn/public/user/pages/03.themes/04.twig-filters-functions" at line 491.
> For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

**Comment by mahagr** [comment]
Should be working now.
