### ISSUE TITLE
Cache check page option unclear

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-learn#885]
https://learn.getgrav.org/16/advanced/performance-and-caching
https://github.com/getgrav/grav-learn/blob/develop/pages/08.advanced/02.performance-and-caching/docs.md

> The `cache: check: pages:` option can provide some slight performance improvements, but this will cause Grav to not check for any page edits. This is intended as a Production-only setting.

This setting `cache: check: pages:` is unclear to me. To what value should it be set? Is it even still valid? Or should it rather be `cache:  check: method: none`? The doc is older than 2014, it may be outdated.

**Comment by rhukster** [comment]
I think it's an old setting before we had the `cache.check.method` option.  I can find no reference to it.  I think that documentation should be removed.

**Comment by NicoHood** [comment]
I've suggested a fix here: https://github.com/getgrav/grav-learn/pull/886
