### ISSUE TITLE
Dead link for more info

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-learn#89]
I don't know how to fix the `more info` link in Markup for:
`data-srcset | In case of image media, this contains the srcset string. (more info)`

`http://learn.getgrav.org/content/media/#responsive-images`
should be:
`http://learn.getgrav.org/content/media#responsive-images`

**Comment by rhukster** [comment]
Yah slight bug crept into Grav in last release.. Workaround is to use

```
 [responsive images](../media#responsive-images)
```
