### ISSUE TITLE
Code breaks TOC

### ISSUE THREAD

**Issue by xf-** [getgrav/grav-learn#935]
## Example
https://learn.getgrav.org/17/forms/forms/form-options

## issue
Code-copy overlays the TOC and unable to click.

## Fixes
1. Maybe move Code to deeper wrapper, so it is like UI and not full width
2. Give `.prism-wrapper` `display: grid`

**Comment by rhukster** [comment]
Thanks has been fixed with overflow: hidden.  Thanks!
