### ISSUE TITLE
http://twig.sensiolabs.org/ links not working in 'Step 4 - Base Template'

### ISSUE THREAD

**Issue by prasannakulkarni333** [getgrav/grav-learn#960]
Below external links in themes tutorial step 4 are not working http://twig.sensiolabs.org/doc/tags/extends.html & http://twig.sensiolabs.org/doc/tags/block.html

This is currently on URL - https://learn.getgrav.org/17/themes/theme-tutorial#step-4-base-template

Not sure what a good substitute here would be.

**Comment by rhukster** [comment]
Why not just click the edit button on the page and make the changes?  It will create a pull request.
