### ISSUE TITLE
Exception thrown for 'js_module_pipeline' in local install

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-learn#977]
I have been using a local install for docs modifications that become PRs. It has been working fine but now on the homepage I see:

```
Server Error

Sorry, something went terribly wrong!
0 - An exception has been thrown during the rendering of a template ("Property 'js_module_pipeline' does not exist in the object!").
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

and `bin/grav log` shows:
```
[CRITICAL] An exception has been thrown during the rendering of a template ("Property 'js_module_pipeline' does not exist in the object!")
```
Not sure if this is related to b922fed. I've tried disabling JS pipelining and JS module pipelining to no avail.

**Comment by rhukster** [comment]
What version of Grav is this?  Latest?  You should have this property defined on line 91 of Assets.php

**Comment by hughbris** [comment]
Sorry that was remiss of me not to check. Couldn't easily find out with errors, but have updated and now works.
